language: python
python:
  # - 2.6
  - 2.7
  # coverage no longer supports Python 3.2
  # - 3.2
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install: pip install -r requirements.txt -r test-requirements.txt
script: nosetests --with-xunit --cover-erase --with-xcoverage --cover-inclusive --cover-html --cover-package=autojenkins autojenkins
