#!/usr/bin/python

from autojenkins.run import *


parser = create_opts_parser('delete')

(options, args) = parser.parse_args()

if len(args) == 2:
    host = args[0]
    jobname = args[1]
    delete_job(host, jobname)
else:
    parser.print_help()
