#!/usr/bin/python

from autojenkins.run import *


parser = create_opts_parser()
(options, args) = parser.parse_args()
if len(args) == 2:
    host = args[0]
    jobname = args[1]
    run_jenkins(host, jobname, options)
else:
    parser.print_help()

